version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  user_app:
    platform: linux/x86_64
    container_name: user_app
    image: chandra/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - user_db

  user_db:
    platform: linux/x86_64
    container_name: user_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data